spring:
  application:
    name: core-pedidos-v1
  datasource:
    url: jdbc:postgresql://localhost:5432/pedidos_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  batch:
    job:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: validate          # Flyway maneja el esquema, no Hibernate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 10         # Tamaño de lote configurable (requisito del enunciado)
        order_inserts: true       # Necesario para que el batch funcione real
    show-sql: false

  flyway:
    enabled: true     # Habilitar Flyway
    locations: classpath:db/migration
    baseline-on-migrate: true

#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html

pedidos:
  batch:
    size: 10

logging:
  level:
    root: INFO