package michael.page.domain.model;

public enum TipoError {
  NUMERO_PEDIDO_INVALIDO,
  FECHA_ENTREGA_INVALIDA,
  CLIENTE_NO_ENCONTRADO,
  ZONA_INVALIDA,
  SIN_SOPORTE_REFRIGERACION,
  ESTADO_INVALIDO,
  DUPLICADO,
  ERROR_FORMATO
}
